### ISSUE TITLE
Replace uBlock Extension With Disconnect Extension

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/twitchy-desktop-lite#17]
Ublock is making problems and a switch to Disconnect should fix it and also come with general performance improvements. (Privacy is also a lot better with Disconnect.)

Disconnect Link: https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo?hl=en

**Comment by TheRealDannyyy** [comment]
Nevermind this is an issue with Twitchy, maybe adblock doesn't load or work correctly.

**Comment by TheRealDannyyy** [comment]
This might be an alternative if we can't get adblock working: https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf

**Comment by TheRealDannyyy** [comment]
We should replace ublock with Disconnect for adblock and general performance speedup.
Disconnect Download: https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo?hl=en

**Comment by TheRealDannyyy** [comment]
@Armaldio Did this already happen?

**Comment by Armaldio** [comment]
yes
