### ISSUE TITLE
Create Feature Roadmap/To-Do For Developement

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/twitchy-desktop-lite#2]
We need a clear document with all the stuff that needs to be done. 
Through 3rd party service or simple text file?

**Comment by Armaldio** [comment]
You can do that with the "Project" tab

Le ven. 25 mai 2018 à 18:11, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
You need to enable it again since I have no access to repo settings.

**Comment by Armaldio** [comment]
Done

**Comment by TheRealDannyyy** [comment]
Thx, checked it out and it's great. Will finish it sometime soon.
