### ISSUE TITLE
Add "Starting Page" For Twitchy Desktop Lite

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/twitchy-desktop-lite#4]
## Starting Page Basics
The starting page should be shown to users starting the application for the first time. Here users will be able to select their extensions for use on Twitch. Clicking on "Save & Continue" will then detect which extensions will be used, install them, "restart" the application (if needed) and directly open up _Twitch.tv_.

If the checkbox isn't checked, the starting page will be shown again when the application is started again. 
If the checkbox is checked, it will directly open the _Twitch.tv_ website.

(Important: Access to the settings menu should be blocked while being on the starting page!)

## Starting Page Features
- Basic layout with extensions and buttons to enable/disable them
- Button to save & continue
- Button to hide starting page (default = checked)

## Starting Page Concept
![startpage_concept](https://user-images.githubusercontent.com/15656049/40555817-9d7c2b6c-604a-11e8-8134-44c0ba7a2a69.png)

**Comment by TheRealDannyyy** [comment]
I would like to completly drop this idea of a starting page. It's totally against everything Twitchy stands for and adds another annoying layer between the content and the user.

I propose a change to instead show a notification to open settings and have all extensions enabled by default. Would you agree to do that instead?

**Comment by Armaldio** [comment]
Sure!

**Comment by TheRealDannyyy** [comment]
Closing, please remove everything starting page related and keep the usual starting processes (e.g. 1st time extension download + updates)

**Comment by TheRealDannyyy** [comment]
Closing, please remove everything starting page related and keep the usual starting processes (e.g. 1st time extension download + updates)
